### ISSUE TITLE
どのライセンスでリリースされていますか？

### ISSUE THREAD

**Issue by fu7mu4** [sys1yagi/AndroidPractice#1]
素晴しいソースコードを公開していただき大変ありがたいのですが、
ライセンスがわかりませんでした。
ライセンスをソースコード中のテキストファイルで指定していただけないでしょうか？

**Comment by sys1yagi** [comment]
う、すいません。MITにします。

**Comment by fu7mu4** [comment]
LICENSE というテキストファイルをおいて http://opensource.org/licenses/MIT からコピーしていただくと助かります。

**Comment by sys1yagi** [comment]
done 1ed8c74ec809f0b91d32ef4a5dc040914fe8df3c
